### ISSUE TITLE
Modals near the end of the page - Support

### ISSUE THREAD

**Issue by thinkstudeo** [alpinejs/alpine#105]
As per the best practice code for modals must be just before the closing body tag to avoid unintended cascading effects of css.

Lets say we have a data table of todos with a delete button on each item somewhere in the page. When a user clicks on the delete button a warning about the destructive action `delete` must be shown to the user asking for confirmation. The `ConfirmDeleteModal` should ideally be inserted in the code for modal just before the `</body>` tag.

Frameworks like vue support such use case via `portal-vue`. How to achieve the same with `alpine.js`?

This is a basic functionality which may be needed in most projects - I guess - so including a support for such use case will definitely be helpful for people like me who are excited about replacing frameworks with `alpine.js` in projects where routing can be managed via server backend like lavavel.

**Comment by thormeier** [comment]
This would require some kind of inter-component communication. An existing one is `$parent` which lets you call functions and alter attributes of the immediate parent component. Since such a modal lives right inside the body, a component on the body might allow you to do this.

@calebporzio When I think further about this, what would be your opinion on something like `$root` to get the outermost component and thus allow a "global" state?

**Comment by rzenkov** [comment]
Portals works for Vue and other by design, component (when created) can be mounted at any parent. But for alpine we have prerendered html (from backend), Alpine creates components around it, excepting `x-if` and `x-for`, which renders html, but inside already mounted component.
Imho best way for doing this modals in Alpine way - using events.
Here some code for illustration:

```html
 <table>
    <tr x-data="{id:1}" @removed.window="$event.detail.id == id && $el.remove()">
      <td>element 01</td>
      <td><button @click="$dispatch('remove',{id})">Remove</button></td>
    </tr>
 </table>
```

```html
  <divx  x-data="{show:false,id:0}" :class="{show}" @remove.window="show=true;id=$event.detail.id">
    <div>
      <div>A you sure?</div>
      <div>
        <button @click="show=false;$dispatch('removed',{id})">Ok</button>
        <button @click="show=false">Cancel</button>
      </div>
    </div>
  </div>
```

[JsBin example](https://jsbin.com/tununuj/edit?html,output)

**Comment by thinkstudeo** [comment]
Thanks for the code and bin @rzenkov 

Will try this out

**Comment by calebporzio** [comment]
Yeah, I'd like to avoid patterns that force people into bigger and bigger Alpine components (which would be the case when relying on something like `$root` and even `$parent` all the time)

I'd rather do the event dispatching and listening stuff.

It's a trade-off, but that's the current direction of the framework.
