### ISSUE TITLE
Error using a dash in the ref name

### ISSUE THREAD

**Issue by tao** [alpinejs/alpine#1246]
I was trying the pre-fetch partial demo in the README. I noticed I was unable to use `$refs.mobile-nav` however `$refs.mobilenav` works fine.

The error response is as follows:

```js
Alpine Error: "SyntaxError: Left hand side of operator '=' must be a reference."

Expression: "fetch('/nav/mobile-nav').then(response => response.text()).then(html => { $refs.mobile-nav.innerHTML = html })"
```

I also tried `$refs[mobile-nav]` from the dynamic refs issue #252 but that didn't seem to help.

Perhaps it would helpful to add a warning to the documentation about this if it's just a javascript thing?

**Comment by Ryuno-Ki** [comment]
I could imagine, that `$refs['mobile-nav'].innerHTML` would work.

**Comment by HugoDF** [comment]
> I could imagine, that `$refs['mobile-nav'].innerHTML` would work.

👍 this should indeed work.

Background note: the reason `$refs.mobile-nav` doesn't work is that JavaScript doesn't consider `mobile-nav` to be a valid property access (the `-` breaks the compiler), so crashes, to access `mobile-nav` key you need to use the square bracket ("dynamic property access") notation ie. `['mobile-nav']`, which works because `'mobile-nav'` is a valid string in JS.

Closing this since it's more of a JavaScript question and probably not an Alpine bug.

Feel free to open a [discussion](https://github.com/alpinejs/alpine/discussions/new) if you still encounter the problem after trying the suggested solution.
