### ISSUE TITLE
Unable to x-model a disabled option within a select element

### ISSUE THREAD

**Issue by tomwelch** [alpinejs/alpine#1266]
I often use disabled options in select elements as placeholders, but I can't get that to work with Alpine. I'm not sure if this is a bug or intentional.

### Example
https://jsbin.com/lezusiyare/edit?html,css,output

### Expected behaviour
The disable option (Choose an option) should be selected

### Current behaviour
The first option (Option one) is selected

### Notes
I've included an example without Alpine that demonstrates the browser native behaviour that I'd expect to be replicated in Alpine.

**Comment by KevinBatdorf** [comment]
Your markup on the "with" and "without" parts are different. And if you make them the same, the results are identical.

**Comment by tomwelch** [comment]
Sorry, yes I was messing around with hidden vs disabled. I've updated the example to use disabled on both. You'll see the "with" example is still defaulting to "Option one" rather than "Choose an option"

**Comment by ryangjchandler** [comment]
The problem is in this function here: https://github.com/alpinejs/alpine/blob/6c7e6e0ae906e3f7f20343ec079feafa8f444bde/src/directives/bind.js#L86

Not dug into it properly, but at a glance I think the `option.value || option.text` is causing issues.

**Comment by KevinBatdorf** [comment]
That's right. There should be a special check for an empty value since in this case you'd want that option to be selected. You'd want to keep the `||` too I think since often the value and the text aren't the same.

**Comment by KevinBatdorf** [comment]
Maybe something like this?
```js
option.selected = value + '' === option.value || arrayWrappedValue.includes(option.value || option.text)
```

**Comment by SimoTod** [comment]
I think the or operator is not correct there because it would discard any falsy values (like 0).
Javascript has a null coalescing operator `??` which would probably work better. 
Not sure why Alpine needs to compare the text, anyway, it should really bind to the value imo (and I think browsers automatically returns the text when value is not present without that hack).

**Comment by KevinBatdorf** [comment]
Removing that check would break functionality for anyone who has a `value` and sets the `select` model with the text value. Not that I'd recommend anyone doing that, but I can imagine it happens.

`<option value="no">No</option>` for example, would break if the select's `x-model` was set to `No` rather than `no`

**Comment by SimoTod** [comment]
> `<option value="no">No</option>` for example, would break if the select's `x-model` was set to `No` rather than `no`

That would not select it anyway at the moment, right? `option.value` is not falsy so `option.value || option.text` resolves to `"no" || "No"` therefore `"no"`
