### ISSUE TITLE
:class bindings and x-transition are not compatible

### ISSUE THREAD

**Issue by danfascia** [alpinejs/alpine#156]
Transitions don't work if you also have a `:class` binding on the same element as the `x-transition`. I would imagine that this is something to do with a conflict of multiple events trying to write to the `class` but it's pretty inconvenient.

Has this been noticed before and is there any workaround?

Here is an illustration of the problem, if you trigger an error message by clicking any button then I have created two error messages, one with and one without the `:class` binding to show the issue.

https://codepen.io/danfascia/pen/dyPrwvB?editors=1010

**Comment by danfascia** [comment]
OK, so I've updated and documented in the codepen a solution but it is a workaround.

By separating the `:class` binding and `x-transition(s)` onto different `<div>` elements I can make it work as expected but I still think it is a bit of a bug.

**Comment by danfascia** [comment]
@calebporzio is this a known issue / intended feature or do you think it is worth adding something to the docs about the incompatibility?

**Comment by SimoTod** [comment]
I don't think it's the desired behaviour so it will probably be fixed in one of the next releases. Another workaround for now, since Alpine processes its directives in order, is to put `:class` before `x-show`.

**Comment by danfascia** [comment]
That's interesting, I think I've spotted that since there were inconsistencies in producing this behaviour. Would be good to fix.

**Comment by calebporzio** [comment]
Ok, yeah I think this is a legitamate bug and should be addressed. Would someone mind doing some exploration into the problem to make things easy for me (if not PRing the entire solution/test itself) - Thanks!

**Comment by SimoTod** [comment]
I think the issue here is that we store the original classes when a component is initialised and `:class`, every time is recalculated, wipes out the old classes and restore the original classes + its own result.

This could also be annoying if, in the meantime, a different piece of javascript added some classes to the element.

On the other hand, we can't read the current classes and use them because they will contain results from the previous evaluation of :class that we may want to remove.

**Comment by ryangjchandler** [comment]
Hey everyone that was on this thread - I forked the original CodePen and updated to latest version of Alpine and tested and I couldn't see any problems with the class bindings and transitions (https://codepen.io/ryangjchandler/pen/JjXGZyK).

I'm going to close this issue for now since there wasn't much information on the problem in the first place, but @danfascia if you still think this is a problem, please re-open this issue and let us know (with some new example). Cheers! 🙂
