### ISSUE TITLE
Alpine interaction with Custom Elements and Shadow DOM

### ISSUE THREAD

**Issue by tmalaher** [alpinejs/alpine#172]
I've been doing a bit of experimentation with native custom elements (aka Web Components).
See <https://developers.google.com/web/fundamentals/web-components/>

The immediate problem is that in index.js the `discoverComponents` function uses `document.querySelectorAll('[x-data]')` to find the components. This does *not* find elements that live in a shadow DOM. (Even in "open" mode.)

Thus no Alpine functionality works within a custom element.

Likewise in utils.js the function walk will not recurse into the shadow DOM elements, and thus in component.js `walkAndSkipNestedComponents` will not find elements with x-data attributes inside custom components.

As a small experiment, i created my own "walk" function that added something like this:
```javascript
//...
walk(node, callback)
if (node.shadowRoot) { // recurse into shadow DOM if custom component found
    walk(node.shadowRoot,callback);
}
//...
```

To handle custom components, one can create a modified version of discoverComponents:
```javascript
discoverComponents: function(parent,callback) {
        const rootEls = parent.querySelectorAll('[x-data]');
        rootEls.forEach(rootEl => {
            callback(rootEl)
        })
}
```

And then call it either with `discoverComponents(document,...)` or `discoverComponents(el.shadowRoot,...)`

However, that would mean that we would need to walk the entire DOM, searching for custom elements, rather than being able to make a single call to `querySelectorAll`. One could imagine this being a performance issue.

These are just the beginnings of a discussion about making custom elements available to Alpine.

I realize that this is slightly beyond the original design of the library, which was intended to add interactivity to server-side generated HTML, and thus there is no need for custom elements, as the server could simply construct the required repeated boilerplate, thus obviating the need for custom components.

But I wanted to see if a combination of Alpine and Custom Elements could be a very lightweight replacement for Vue (or other frameworks) using native browser functionality as much as possible.

I'll do some more thinking and experimentation and post the results as comments here.

**Comment by SimoTod** [comment]
I did some exploration weeks ago seems I think it could be an interesting idea but I'm not sure that using the shadow DOM would follow the design of the library (we would end up with hiding everything again, the only difference would be that we use the shadow DOM instead of the virtual DOM).

My experiment was just about using a web component to pack a chuck of html and render it in the real DOM.

https://codepen.io/SimoTod/pen/xxbedqb

I'm looking forward to knowing your findings, though.

**Comment by tmalaher** [comment]
Interesting. Your example works because you just replace the innerHTML of the custom element, and don't attach a shadow DOM.

The Virtual DOM that other frameworks create is purely an internal data structure, whereas the Shadow DOM is a standard browser feature. So it's not "hidden" in the same sense...

I can probably get by with the innerHTML trick for now and avoid the Shadow DOM problems.

But the Shadow DOM gets you all sorts of useful things like scoped styles, parameterized content slots and custom events that might make life much easier in the long run. However these are exactly the types of things that would make the Alpine library code much more complex.

The abstractions provided by Shadow DOM might be more useful for someone writing a component library, whereas if the custom elements are hog-tied (i.e. tightly coupled) to my exact CSS and Javascript context, I can probably make it work.

**Comment by SimoTod** [comment]
Hi @tmalaher, I've tried your suggestions for a custom component using the shadow DOM.
The main blocker for a component library, in my opinion, is how we style the shadow DOM from outside. For example, if we have a modal component, devs must be able to change fonts, colors, etc.
How did you approach that? Did you define css hooks for everything in your component?

**Comment by tmalaher** [comment]
CSS Styling is definitely one issue, but even using custom components with plain static HTML you would have that problem (which is really one of API design for the component author).
My concern is more about dynamic behavior/content (x-data, @click, x-model, etc.)
Certainly there is an overlap when you get to the class and x-show, but at the moment I think most of the problem is how to get the javascript parts (data, behavior) to work.

But maybe I'm thinking about this the wrong way. Once the component is packaged up so that it has its own local javascript, how do you pass dynamic data from the parent (calling) page into the component so the component can use it to modify the shadow DOM?

My first thought was to use slots and pass HTML Elements into the component that it would inject into its shadow DOM. This fails because alpine does not delve into the shadow DOM instances looking for x-data attributes. So I thought we would need to extend alpine to understand shadow DOM structure and inspect the contents. This way the component itself would not need to know anything about alpine.

Is there a better way? Can we design a component that is alpine-aware such that it can "pull" data in from an x-data attribute on the root element of the custom component?

I believe that anything beyond a toy solution is going to need to use a shadow DOM, and can't just use innerHTML.

**Comment by cekvenich** [comment]
I'll add 2c in case it helps. I agree that innerHTML is not a real solution. Custom Elements(CE) is a standard and... things should be built on top of it, not around it. It defines a way to set attributes via .js or declare inline html (like tailwind). However, CE is not reactive. (and I use it w/ a global event bus to solve all issues).  And I can see that it would not be a lot of work to create a base CE that has all the directives and properties into a BaseAlpineElement. I'd be happy to contribute some effort if this becomes a direction for Alpine v3. You would then extend a BaseAlpineElement to make MyCE and place that in html, and have all the directives and properties baked in, the html syntax would be very similar if not same. Happy to comment more if needed.

**Comment by SimoTod** [comment]
@thormeier My second attempt was just about modifing walkAndSkipNestedComponents to look for elements in the shadowDOM. 

At least for the first iteration, it made sense to me to pass the x-data from the original DOM and just support other directives. We can also use slots (we can have modals, dropdown, etc) to pass the content we need to change, and that would work.

If it's just for internal purposes where you already know the style that you want to use, it will be okay.
I was thinking that, if you wanted to distribute that component, it would be really hard to style for other devs so from that point of you styling is a major problem. Normal HTML would follow the standard CSS rules but CE are sandboxed by design so styles don't leak in or out.

The changes to the Alpine core would be minimal so I think it could make it into the core.

@cekvenich It's another valid option. It probably doesn't need to be in the core but it could be an extension that you pull in if you don't need any core changes so maybe it doesn't even need to wait for v3 (talking about the idea, I haven't figure out if you need to hack in the core). I assume the styling problem will still be there. I create a generic modal component, my user want to make the title red, but the html tag is in the shadow DOM, how do they style it?

**Comment by cekvenich** [comment]
@SimoTod I do want to see your implementation for CE when it's ready.
As to style, I think the real answer is that CE is the standard way of doing it, and that we'll be in the same boat as everyone else going forward - some design patterns will emerge. The answer to your question depends on open or closed? and then get it to work. I have also imported the same style sheet in 'main' page and in each CE as a base, and from there customize.

**Comment by SimoTod** [comment]
@cekvenich I'm not going to be home this weekend, I'll share my work in progress on Monday. 👍

**Comment by cekvenich** [comment]
@SimoTod This is all open-source volunteer work so enjoy yourself as much as you can.

FTW, here is my hello world CE impl:
- https://github.com/intuition-dev/mbToolBelt/tree/master/custel/custel1

**Comment by SimoTod** [comment]
@cekvenich Thanks for sharing, I'll have a look.

This is my work in progress -> https://github.com/alpinejs/alpine/compare/master...SimoTod:feature/custom-components?expand=1

I said walkAndSkipNestedComponents but I was typing from my phone and I didn't remember the right name. What I changes is the walk function. As you can see the change is really small so including it in the core is not unrealistic, I think.

Here is an example(the component is really dumb, i know, it's just to show the concept) -> https://codepen.io/SimoTod/pen/OJVzyzZ

Known limitation: You can't define whole alpine components in the shadow DOM
Stuff like:
```javascript
class ReusableComponent extends HTMLElement {
    constructor() {
        super();
        const shadowRoot = this.attachShadow({mode: 'open'});
        shadowRoot.innerHTML = `
            <div x-data="{ foo: 'bar' }">
                <input x-model="foo" />
                <slot name="content"></slot>
            </div>
        `;
    }
}
window.customElements.define('reusable-component', ReusableComponent);
```
would not work but it makes sense to me that x-data should be passed in from the light DOM.

**Comment by cekvenich** [comment]
@SimoTod For sure you can pass x-data attribute to a CE. I'd be happy to write a full example if you want? But since it is open-source,  it maybe be the weekend before I get to it, but let me know.

**Comment by SimoTod** [comment]
@cekvenich Yeah, there will probably be a smart way but I haven't focused on that part much since I was more interested in the general concept. 
it may be tricky since the discoverComponents function uses a DOM selector but I'm not sure if there is a smart way to query all the shadow DOMs. Maybe we can use an Alpine-Aware component as you suggested and inherit from that one. Feel free to experiment whenever you can, I'll do the same when I have some spare time.

**Comment by cekvenich** [comment]
@SimoTod Will do. One obvious way is an eventBus. It may eliminate the need to discover.  But lets play.

**Comment by ryangjchandler** [comment]
Hey guys, I'm going to close this issue since it's been stale for a few months now. If anybody wants to investigate Alpine & Web Components further, please re-open this issue and let us know your thoughts and ideas, or even better, open a new [Discussion](https://github.com/alpinejs/alpine/discussions/new) which is where we try to keep all of our feature requests. Cheers! 🙂

**Comment by georges-gomes** [comment]
A working Web Component with AlpineJS
https://webcomponents.dev/edit/4oNbCTP7NCFJftyKer7j

But obviously no support for ShadowDOM...

Would it be easy to pass the `shadowRoot` to AlpineJS so he can "hook" it up?
Something like that

```
// Pseudo code
connectedCallback() {
   this.shadowRoot.append(template.content.cloneNode(true));
    Alpine.hook(this.shadowRoot);
}
```

Is this possible?

**Comment by MarcGodard** [comment]
My whole app uses this approach and `Spruce` for global data sources. I have completely usable components doing this. No shadow DOM being used. So far, the only draw back to this approach is that the javascript garbage collector sometimes doesn't move fast enough and the app slows down for a while. Other than that tho, this approach has been very successful.

**Comment by AdamGulmantowicz** [comment]
Hi guys,
What about @SimoTod implementation of shadowDOM support? I think it would be great idea.

**Comment by MarcGodard** [comment]
I am now really putting effort into exploring this. 

This is what I am doing for my CEs:
- I create a model using `Spruce` for each CE (so they can be loaded as needed).
- I am using tailwind purge and gulp scripts to make CSS for each CE (so making shadow dom should be easy CSS wise). Still have some improvements to make to this.

However, I am starting to see slight performance issues now that the app is growing (I have about 30 CEs now). And would love to help out anyone that is interested in working on a plugin or something to make shadow dom work.

my x-data is completely empty and everything is done with Spruce and vanilaJS. @ryangjchandler Do you know if Spruce can be used across shadow dom? I would assume easily, but new to shadow dom stuff.

I find this all with dynamic loading / imports make a very handy little "framework" that is actually very powerful, especially if shadow dom ability is added.

**Comment by MarcGodard** [comment]
Can we re-open this? I am ready to support a bounty to add this type of support.

**Comment by james0r** [comment]
This is maybe more tightly coupled than people's liking, but using event listeners and targeting the Alpine component head of nested web components worked for me for this simple demo at least.

https://codepen.io/James0r/pen/vYZBrRj

**Comment by mindplay-dk** [comment]
I don't know how much this relates to the discussion here - but I did manage to create a basic, working web-component from a `<template>` tag with Alpine markup inside it.

https://github.com/alpinejs/alpine/discussions/2825

It looks like the `MutationObserver` in Alpine was supposed to initialize `x-data` roots when they're added, but that doesn't happen - probably, as others have pointed out, because of `querySelectorAll` not piercing the shadow DOM.

So in this implementation (in the post above) I manually call `Alpine.initTree` on the shadow root, from `connectedCallback` in the custom element, and that seems to work.

I think what I'm trying to do here is a bit different from what you guys were trying to achieve? Just posting this in case it's somehow helpful for what you're trying to do. 🙂

**Comment by vedantroy** [comment]
+1 this.

My use case: I have a chrome extension. I have event listeners on the main page that should trigger a change inside a shadow DOM. For example, I might have a injected button that is inside a shadow DOM. When the user clicks somewhere on the main page, I'd like to show the button in the shadow DOM.

**Comment by priand** [comment]
Hello - AlpineJS is a great technology for web components, precisely because it is not entirely focused on web components. I created this sample code to create reactive custom elements using either ShadowDOM or LightDOM: https://studio.webcomponents.dev/edit/xohIW3rpMCBHeducM4sw/README.md.  

I'd love to get the feedback of AlpineJS experts, particularly regarding how the reactive state is managed. The patterns are explained in the README and within the code. I'm wondering if some runtime additions can make it even more natural.  

I also created a few utilities that I would love to see added to the project, at least in a web component plugin:

- `$wc`:  a magic that returns the component host, so an expression can access any public component member (ex: `$wc.myAction()`). Note that it only works with ShadowDOM.  
- `x-prop` & `x-props`: to set the element properties, which allows a caller to pass any JS values while attributes are restricted to string.  `<my-component x-prop:data="myobject"` or `<my-component .data="myobject"`, to mimic LitElement.

After diving into the implementation, I believe that piercing the ShadowDOM when building the scope for an element is violating the web components principles: if a state/value has to be passed to the component, it should be done via an attribute or a property, and should not rely on the caller technology.  

```
    if (typeof ShadowRoot === 'function' && node instanceof ShadowRoot) {
        //return closestDataStack(node.host)
        // Should be:
        return []
    }
```

Please let me know what you think!

**Comment by mkeida** [comment]
import Alpine from 'alpinejs';
import template from '../views/th-button.html';

export default class ThButton extends HTMLElement {
    constructor() {
        super();
        this.attachShadow({ mode: 'open' });
        this.shadowRoot.innerHTML = template;
    }

    connectedCallback() {
        Alpine.initTree(this.shadowRoot);
    }
  }

This works perfectly 😊

**Comment by Gioni06** [comment]
@priand love your solution! Even works with Declarative Shadow DOM 🚀
