### ISSUE TITLE
Suggestion: add x-show.transition.translate-x and x-show.transition.translate-y

### ISSUE THREAD

**Issue by lucasromanojf** [alpinejs/alpine#182]
Hey @calebporzio !

Very good idea to add the x-show transition helpers. I'd just like to suggest adding translate helpers too (see https://tailwindcss.com/docs/translate) for using with navigation drawers (translate-x) and/or action sheets (translate-y).

I think translating from 0 to 100% (and also -100%) and the opposite (out) are the most common use case, not sure if adding a parameter for measure is necessary since this can be achieved with x-transition.

**Comment by mokhosh** [comment]
+1

**Comment by SimoTod** [comment]
I'm aware it's a really old issue but I didn't notice at that time.
What's the benefit over using css classes (like the ones from tailwind css)?

It would set a precedent where someone needs another visual setting and instead of using they expect Alpine to do templating stuff. I don't think the amount or expressivity of the resulted code would change as well.

Do you have an example where it would improve the current behaviour? Thanks

**Comment by ryangjchandler** [comment]
Hey guys, I'm going to close this issue since the original author never replied or followed up and it has been stale for a little while. Personally, I think this is outside of Alpine's scope and as @SimoTod said, it is a templating feature that can be achieved using `x-transition` utilities or class bindings.
