### ISSUE TITLE
Remove x-* attributes from dom markup after parsing?

### ISSUE THREAD

**Issue by jasonlfunk** [alpinejs/alpine#261]
Is it possible to have the `x-*` attributes removed from the dom markup after it's parsed? Or is there a good reason that I should want them to stick around?

**Comment by HugoDF** [comment]
What problem are you trying to solve by removing them?

Removing the attributes would involve updating a bunch of attributes on a bunch of DOM Nodes, that's gonna have performance implications.

**Comment by jasonlfunk** [comment]
It's not really a problem to solve... just coming from vue when I opened the dev tools in my browser I wasn't expecting to see my DOM cluttered up with these attributes. I wanted to ask the question to see if there was a reason that it was decided not to remove them after reading them.

**Comment by HugoDF** [comment]
Sure so the difference in this case is that Vue.js takes the template, creates a virtual DOM (in-memory representation of what the template looks like) and then writes it to the actual DOM.

During the "create virtual DOM" step or the "write to DOM" step, it's very cheap to strip extra attributes since it's just a case of not putting them into the final DOM representation.

Alpine's templating is HTML-based and pretty much just watches the DOM and updates it, no virtual DOM. So stripping the attributes would require more code and effort since you would need to check attributes and remove them from the DOM as you walk through it.

I think we probably just need "Alpinejs devtools" that will give you the pretty view without the clutter 😊

**Comment by jasonlfunk** [comment]
Thanks for the info. :)

Just out of curiosity - isn't alpine already walking the DOM to find all the `x-*` attributes during initialization and generating some sort of internal model anyways? Is it really that much more of a performance hit to remove the attribute during initialization?

**Comment by SimoTod** [comment]
if you remove the `x-` attributes, with the current implementation, you will remove the reactivity as well.
Alpine is still relying on those attributes when refreshing the component since it doesn't have a virtual DOM to map them.

**Comment by jasonlfunk** [comment]
Perfect. :+1:

Thanks!

**Comment by HugoDF** [comment]
Yeah it's walking already.

 I don't think it would be a massive perf hit, for every node loop through attributes and remove them.

I just don't know that there's a compelling reason to do it, it's extra code, extra cycles when running the app, for a slight "prettification" benefit if someone inspects the page?

You lose the ability to reboot the Alpine.js app (if you ever need to do that) since you've stripped the relevant attributes. And it makes the code less "inspectable" for third parties since you only see Alpine.js operations instead of the initial source.

**Comment by joydeep-bhowmik** [comment]
Alpine js is not as advanced as Vue yet....

**Comment by joydeep-bhowmik** [comment]
> > Alpine js is not as advanced as Vue yet....
> 
> Yes, and it'll never be, and that's by design. These two are for very different use cases. If you want something as advanced as Vue, you're better off with Vue.

Yeah but  Petite vue removes all the attributes. Alpine could have done something similar but now I guess it's to late to do that

**Comment by joydeep-bhowmik** [comment]
> Oh okay. That makes sense. I assumed you meant the main version of Vue. Tho I wouldn't call Alpine less advanced than Petite Vue

I mean surely alpine js has more directives but 
v-pre
v-once
reactive()
nextTick()
v-effect
@vue:mounted & @vue:unmounted
And also a component system 

Seems pretty ahead ....but it's almost a abandoned project so doesn't matter

**Comment by wimurk** [comment]
It's almost 5 years later and i was wondering if there is any change this was implemented? 

I have templates like 
```html
<button data-bs-toggle="tooltip" class="btn btn-outline-primary w-100 mb-1" type="button" x-on:click="addSubCategory(subCategory)" x-bind:class="replacementsFilters.subCategories.includes(subCategory.id) ? `btn-info text-white` : `btn-danger`">
    <label x-text="subCategory.name">spoelrandvrij verdekt</label>
    <template x-if="activeInventoryProduct.data.basic.subcategory_id === subCategory.id">
        <span class="badge bg-primary">Basis</span>
    </template><span class="badge bg-primary">Basis</span>
</button>
```

Would be nice if the x-* would not be visible in the dom.

**Comment by joydeep-bhowmik** [comment]
> It's almost 5 years later and i was wondering if there is any change this was implemented?
> 
> I have templates like
> 
> ```
> <button data-bs-toggle="tooltip" class="btn btn-outline-primary w-100 mb-1" type="button" x-on:click="addSubCategory(subCategory)" x-bind:class="replacementsFilters.subCategories.includes(subCategory.id) ? `btn-info text-white` : `btn-danger`">
>     <label x-text="subCategory.name">spoelrandvrij verdekt</label>
>     <template x-if="activeInventoryProduct.data.basic.subcategory_id === subCategory.id">
>         <span class="badge bg-primary">Basis</span>
>     </template><span class="badge bg-primary">Basis</span>
> </button>
> ```
> 
> Would be nice if the x-* would not be visible in the dom.

Try petite vue
