### ISSUE TITLE
adding x-on:swipe

### ISSUE THREAD

**Issue by Haaruun-I** [alpinejs/alpine#290]
I've been using Alpine for a while and it really helps, but I always have to bring in another lib, TinyGuestures to get swipe to work. Wondering if it's possible to add it to alpine directly, I would gladly help add it myself if it gets approved! 

Here is the repo for TinyGuestures: https://github.com/sciactive/tinygesture

**Comment by Haaruun-I** [comment]
I have it working on a fork of this, I can't think of how to test it though, because the `listenerTarget` variable isn't stored anywhere that the tests can access. I don't know the code enough to store it without breaking something though.

**Comment by ryangjchandler** [comment]
Hi @Haaruun-I. You can already listen for custom events using the `x-on:` or `@` syntax. For example, you could listen for `@swipeleft="handler()"`. 

The events that you are referencing are native to TinyGesture, but they're not actually native to JavaScript. You can look at some of the touch events that JavaScript supports here on MDN (https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Using_Touch_Events). 

I'm going to close this issue though, since it's not actually a bug and the support you're looking for is already supported. If you have any problems using the custom event listeners that I mentioned, please open another issue with the details. Thanks! :)
