### ISSUE TITLE
use `xInit` instead of `__init` in future `Alpine.component(...)`

### ISSUE THREAD

**Issue by Lelectrolux** [alpinejs/alpine#321]
I just watched the videos of the "design by comitee" live (30 march).

Alpine already use `x` in templates to it's special attributes, why not just reusing `x` as the alpine prefix in the js side instead of `__`.
Same could be true for future "special" methods if the need arise (`xWatch`).

I just wanted to point this as neither chat nor you (Caleb Porzio) proposed it, as far as I remember. I don't mind either solutions.

Have a nice day

**Comment by calebporzio** [comment]
Thanks, will consider it!

**Comment by thiagomajesk** [comment]
@Lelectrolux @calebporzio
 
I was thinking exactly about that today, but I have a perception that just using a convention, like a calling a `init()` method instead of `__init()` would suffice. I have this impression that those 'underscore' methods could easily be mistaken with some kind of naming convention, eg: 'private functions' or 'metadata functions'.

On the other hand, If we are actually talking about representing those functions as "magic", in the same sense as the "magic variables" Alpine provides, I would vote to reuse the convention of using the `$` prefix. So instead of `__init()` we would have `$init()`, which at least to me, has the clear advantage in conceptual consistency. 

I just wanted to give my two cents, but I know that in the end, it's about personal taste, so it's very debatable 😅.
