### ISSUE TITLE
x-for: Some nested loop issues

### ISSUE THREAD

**Issue by bep** [alpinejs/alpine#323]
I was investigating some odd behaviour with the duplicated output when nesting x-for loops, which I'm not able to reproduce in a simple codepen -- but unless I'm totally mistaken, these 2 looks like bugs:

https://codepen.io/bepsays/pen/mdJoPvd

https://codepen.io/bepsays/pen/ZEGPBXy

The titles in the codepens should be descriptive enough.

**Comment by SimoTod** [comment]
Please use 
`<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.2.3/dist/alpine.js" defer></script>` (or wait until tonight).
Jsdeliver caches the thing for 1 day so if you request 2.x.x is likely to serve 2.2.2 (at least it's what it does for me now).

I pointed out that it wasn't a great idea to use 2.x.x because people will just open a lot of false tickets using the latest features. :)

One of the examples is going to be broken anyway because your sub items have a different structure and you access properties that does not exist (You need at least `sub_items: []`).

**Comment by SimoTod** [comment]
This how your example should look like, i believe
https://codepen.io/SimoTod/pen/MWwxJXz

(Otherwise you'll get error in console)

**Comment by bep** [comment]
@SimoTod thanks, my original problem was also easier to debug after looking in the error console. That problem was originated in nil/undefined values on initial rendering -- which I guess could be improved from Alpine, but I'll close this for now. Again, thanks for the help.

**Comment by SimoTod** [comment]
No worries, it's hard to catch those errors in alpine because, at the moment, it defaults to the global scope when it cannot find a variable or function and we have very little control at that point (unless a good soul writes a fully functional js parser, alpine friendly, so we can get rid of another problem as well) 
Most of the time, the dev console is your best friend while debugging Alpine issues.
