### ISSUE TITLE
$dispatch magic variable is not defined inside a function

### ISSUE THREAD

**Issue by atomgiant** [alpinejs/alpine#355]
I'm not sure if this is a bug or feature request.  Until #49 is implemented I am working on passing data between parent / child components by using $dispatch.

$dispatch works fine if you specify it inline like in the examples from the README.  However, if you call a function such as:

`<button @click="updateCount()">Click me</button>`

And then try to reference $dispatch inside updateCount, it is not defined.

Here is an example of this in action https://codepen.io/atomgiant/pen/ExVYdXz?editors=1111

I also included a workaround which involves passing in the $event to updateCount and calling dispatchEvent with a CustomEvent explicitly.

**Comment by ryangjchandler** [comment]
Thanks for providing an example. Going to say this is a bug, can't see anything immediately wrong with your CodePen, but I'll need to reproduce myself to confirm.

**Comment by ryangjchandler** [comment]
Managed to track down the problem with this one. Will work out a fix now!

**Comment by SimoTod** [comment]
Not sure it's a bug, $dispatch is not a property of the component but it's injected when evaluating a directive to provide a helper.
$dispatch needs to know about the target element so providing a generic one is not trivial.
There have been discussions about adding the feature and defaulting the target to the component root element but it hasn't been implemented.

The easiest way right now is to pass $dispatch into your function rather than $event
See https://codepen.io/SimoTod/pen/mdebaJo (I changed your third example).

This is an old thread about this topic if you are interested (since it's the same request it's probably better to keep a single thread): https://github.com/alpinejs/alpine/issues/143

**Comment by ryangjchandler** [comment]
Well as somebody who didn't know this already, I'd assume that calling `$dispatch` from inside my event handler, it would use the event target as the event target. It's not different to using the `$dispatch` as part of the expression, right?

**Comment by ryangjchandler** [comment]
@atomgiant Please move discussion to the issue Simone mentioned. Thanks!

**Comment by SimoTod** [comment]
Not saying it's wrong. Another guy tried to implement it in the past and it wasn't easy. You can give it a go (it could be that it's easier with the salesforce membrane now). 👍

**Comment by ryangjchandler** [comment]
> Not saying it's wrong. Another guy tried to implement it in the past and it wasn't easy. You can give it a go (it could be that it's easier with the salesforce membrane now). 👍

Yeah I know you weren't saying that, I seemed a bit blunt sorry 😭 

I'll move discussion over to other issue thread. I've got a couple of thoughts :) Thanks for letting me know about the other thread too

**Comment by atomgiant** [comment]
Thanks @SimoTod, @ryangjchandler - I'll close this for now and we can track this in #143.  I hadn't seen that one either.  

I'll chime with any additional thoughts on the other thread.
