### ISSUE TITLE
Allow using x-show on HTML elements with "hidden" attribute

### ISSUE THREAD

**Issue by piotrpog** [alpinejs/alpine#361]
I wanted to use `hidden` attribute to prevent "flickering" of content that is hidden using `x-show` attribute but is visible before JS kicks in. Unfortunately, when `hidden` is present, element never becomes visible.

I managed to walk around this by binding `hidden` attribute to a variable:

```
<div hidden :hidden="hideSomething">content</div>
```

But why don't we make `x-show` usable when `hidden` attribute is present?

**Comment by SimoTod** [comment]
x-show works by adding and removing  'display: none'.
It's just the way it has been designed.

Is it when the page loads? Can you use the x-cloak attribute? At the moment, it's the recommended way to hide element before halpine kicks in and it's a pattern used by many other js framework.

**Comment by ryangjchandler** [comment]
Just add this to your CSS and use the `x-cloak` attribute:

`[x-cloak] { display: none; }`

**Comment by ryangjchandler** [comment]
Hi all, going to close this issue now since a couple of good solutions have been suggested. It's generally best to use what the framework already provides for this sort of use case. 

If you think the behaviour mentioned in the OC is necessary and vital in core, please open another issue with some explanation and reasons why. Thanks! :)

**Comment by mindplay-dk** [comment]
Just my two cents, but I came here to look at the source-code of `x-show` because I couldn't understand why it didn't work with `hidden`.

`hidden` is the semantic HTML standard way to hide elements - it's accessible to screen readers, and the words "hide" and "show" are literally antonyms. I think the only reason CSS `display: none` is more commonly used is because of it's longer history, and accessibility being such a common oversight - but really, in most cases, `hidden` is more appropriate.

I'm not a SEO expert, but apparently `hidden` is also [SEO friendly](https://www.semrush.com/blog/html-hide-element/), ensuring that e.g. the values in your dropdown component example don't show up in search results.

Besides, what looks more semantic and intuitive: this?

    <div style="display:none" x-show="open">

This?

    <div x-cloak x-show="open">

Or **this?**

    <div hidden x-show="open">

I realize I can just replace the plugin on my own projects - but I think it would be nice if the built-in standard directive promoted the use of semantic markup, so maybe this is a change you could slate for a future major release?

**Comment by adnoh** [comment]
I would also need a way to change that behavior as a display:none attribute does not reserve the space anymore which nukes my layout if I hide eg. a tab or accordion element. Setting it to hidden is the way to go.
I understand the "It's just the way it has been designed." - but this doesn't mean necessary that it's still the right way to do it today
