### ISSUE TITLE
Possible to Include Alpine.js into Vue Components

### ISSUE THREAD

**Issue by xyNNN** [alpinejs/alpine#363]
I want to use Alpine.js in Vue Components for simple display logic like menus, dropdowns, what ever.  It's possible to include Alpine.Js logic into a Vue.js Component?

Thanks in advance!

**Comment by HugoDF** [comment]
It's possible, you'll need to include Alpine.js in your build.

If you're doing most Alpine stuff inline (not referencing a function in `x-data`) then it should be pretty straightforward. There are name clashed with things like `$el` and `$refs` and you should use the long-hand `x-on:` and `x-bind:` instead of the shorthand `@` and `:` (since they're also Vue.js shorthand).

If you're referencing a function in `x-data` you'll need to make sure the function is defined as `window.myFunctionName` otherwise when bundled it won't be exposed on the `window`.

I think I might be adding a guide like the one I created for React https://codewithhugo.com/alpine-js-react/

**Comment by xyNNN** [comment]
Great! Thanks!

**Comment by bhekor** [comment]
Thanks

**Comment by AngelCabrera** [comment]
Awesome, I was having troubles with the `:class` and `@click` shorthands, I replaced them with `x-bind:class` and `x-on:click` and everything works as expected.

**Comment by xieyuheng** [comment]
Thanks for the notes in this issue.

Is there any way to use alpine's `$refs` in vue?

**Comment by razvaniacob** [comment]
It seams that I can't make the x-for work in a vue component. any ideas?

**Comment by azzazkhan** [comment]
@HugoDF Is there any chance I can listen for the `click` event on a single element via Alpine and Vue simultaneously? I'm trying to open a modal using Alpine and load the contents using Vue.
