### ISSUE TITLE
[Discussion] Delete statement reactivity problems

### ISSUE THREAD

**Issue by ryangjchandler** [alpinejs/alpine#368]
Opening up a new issue here for some thoughts and discussions on how best to tackle reactivity when using the `delete` statement (following on from #118).

99% of the time, the `delete` statement works fine especially with loops / `x-for`, one thing I have noticed is that other areas of the application are not updated accordingly. 

Take this example of a to do list: https://codepen.io/ryangjchandler/pen/qBOEgjg

Deleting one of the todos will update the list correctly, but it does not cause any reactive changes in the footer area where the total number of todos is. I haven't actually investigated this yet but wanted to see if anyone else had any ideas of what is possibly _could_ be.

To be fair, I might be doing something stupid in there somewhere. I did make some changes to @SimoTod's example from the issue mentioned above and the same problem existed.

**Comment by SimoTod** [comment]
I think it's how js works. 
Calling delete on an array element does not update the length property and does not reindex the array.

If you have:
`items = [0: 'item1', 1: 'item2', 2: 'item3']:3` (this is not js syntax but i hope it makes sense) and you call `delete items[1]`, you'll get back `items = [0: 'item1', undefined, 2: 'item3']:3`.

Basically delete wipes out the portion of memory where the variable was allocated but it doesn't move the other items so the other array indexes don't change.

**Comment by HugoDF** [comment]
The way JS frameworks have historically dealt with this is to say: make a copy of the array/object instead of mutating it. 

I find that the way I write code (because libraries never tackled this) rarely uses delete.

As an aside, it might not be the case any more but "delete" used to cause hard de-optimisation in V8 (Chrome).

I think Vue 3 is dealing with this but have had to implement their own reactive wrapper?

There are also some libraries like [Immer](https://www.npmjs.com/package/immer) and maybe ImmutableJS that tackle this use case without making it an Alpine.js concern.

**Comment by SimoTod** [comment]
More on that topic here -> https://stackoverflow.com/questions/35296768/length-of-the-javascript-array-does-not-change-after-deleting-the-element-from-i#35296828

**Comment by ryangjchandler** [comment]
> More on that topic here -> https://stackoverflow.com/questions/35296768/length-of-the-javascript-array-does-not-change-after-deleting-the-element-from-i#35296828

Never come across this. Thanks both - I very rarely use delete in any applications, will change this.
