### ISSUE TITLE
Support touch events

### ISSUE THREAD

**Issue by umphy** [alpinejs/alpine#370]
It will be great if alpine can support touch events.

**Comment by HugoDF** [comment]
@umphy do you have specific touch events mind?

**Comment by muzafferdede** [comment]
Haha, it is already great!  because It's already supports touch events. Have you tried any of the x-on:touchstart, x-on:touchend ?

**Comment by muzafferdede** [comment]
it is already great! :)  Because It already supports touch events. Have you tried any of the `x-on:touchstart`, `x-on:touchend` ,`x-on:touchmove`,`x-on:touchcancel  `? 

You can basically use any of the javascript events declaring as `x-on:[event]` 
To log event and play around use e.g.: `x-on:touchmove="console.log($event)"`

 Maybe we could clear it in the docs more obvious?

**Comment by umphy** [comment]
Sorry, my mistake. My tests with ```@touchstart``` were wrong.

**Comment by muzafferdede** [comment]
> Sorry, my mistake. My tests with `@touchstart` were wrong.

@umphy it does support `@touchstart` and any other event's using `@` as well. You probably had a typo somewhere.

**Comment by muzafferdede** [comment]
> Sorry, my mistake. My tests with `@touchstart` were wrong.

@umphy it does support `@touchstart` and any other events using `@` as well. You probably had a typo somewhere.

**Comment by umphy** [comment]
Thanks @muzafferdede, as I mentioned before it was my testing mistake. A question though, would it be possible for touch events to prevent click events? It would be helpful for websites where we need to support both devices with and without touch.

If you want, I can create a feature request ticket for this.

**Comment by massimodellarovere** [comment]
One solution for touch event as swipeleft / double tap etc with alpinejs? Best solucion? Thank
