### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by sirinath** [alpinejs/alpine#380]
Alpine is a great framework. More people will discover it and help grow the community if you have a website. You can set up a website on https://js.org/ just using GitHub pages so this is no cost and low maintenance.

**Comment by pohlt** [comment]
I guess it's not a matter of not _knowing_ those resources you mentioned, but more of not _having the time_ to setup a flashy web site. But I'm sure the project owners are open to PRs and other contributions. ;-)

**Comment by ryangjchandler** [comment]
> I guess it's not a matter of not _knowing_ those resources you mentioned, but more of not _having the time_ to setup a flashy web site. But I'm sure the project owners are open to PRs and other contributions. ;-)

Exactly that I think. Currently all of the documentation lives in the README file, which I don't think is a problem since most people are going to come here to find the project anyways and they won't have many problems finding what they need because the API is smaller compared to Vue.

It is definitely something on the radar for the future though, thank you for the suggestion. I'm going to close this issue since there are quite a few duplicate ones out there. Please feel free to make some contributions to the README docs if you think there's anything missing. Thanks! :)
