### ISSUE TITLE
Compatibility with jQuery select box plugins

### ISSUE THREAD

**Issue by pcohen12** [alpinejs/alpine#402]
I've been trying to get Alpine to play nice with [Select2](https://select2.org/) and/or [Selectize](https://selectize.github.io/selectize.js/) (jQuery select box plugins), but in both cases, any Alpine event binding that's set on the `<select>` element doesn't seem to get triggered.

https://codepen.io/pcohen12/pen/VwvmboW

As far as I can tell, `change` events are correctly being triggered on the `<select>` element...my only guess is that Alpine is adding the event listeners first, and Select2/Selectize are clearing all existing listeners for some reason. Does someone smarter than me have an idea of what's going on?

**Comment by HugoDF** [comment]
@pcohen12 That codesandbox has a couple of issues going.

First, you're probably better off initialising `.select2()` in `x-init` (which is an Alpine lifecycle operation) instead of `document.ready()`.

Second, in order to use x-init easily, you probably want to use `x-ref="select"` on your select that you'll `.select2()`.

Third, you probably should programmatically bind to select2 events using `$(select).on('select2:select')`, in the callback to that you can put the data into Alpine.js state and use it.

Working codesandbox to illustrate this https://codepen.io/hugodf/pen/RwWogqq

**Comment by SimoTod** [comment]
Some clarifications about the original example, unfortunately it uses jQuery which doesn't trigger real native Events but it uses custom versions which work with jQuery handlers and on* attributes but don't work with native listeners. See https://github.com/jquery/jquery/issues/3347

For this reason you can't use the x-model directive. Your best shot is to use an implementation like the one suggested by Hugo or to switch to a different select library that doesn't use jquery.

**Comment by pcohen12** [comment]
Thanks much, @HugoDF and @SimoTod !

**Comment by glpzzz** [comment]
Hello! Having a similar issue with FancyTree. When selecting items, it updates the input field correctly, but this update doesn't reflects on the model. The other input that should have the next value is not updated. If you type in this other input, the original does gets updated. 

The change event triggered by `$(selector).val(newValues)` inside the `select` event of FancyTree is not modifying the value in the Alpine.js model. 

 I tried to apply the same principles explained for select2, but no success.

**Comment by vikas-ukani** [comment]
@HugoDF You are awesome, 
Your solution works for me.
Great.
