### ISSUE TITLE
Adding syntax check

### ISSUE THREAD

**Issue by szepeviktor** [alpinejs/alpine#475]
Hello!
I come from the PHP world. There are 3 basic tests _there_: syntax, coding standard, static analysis.

I think static analysis is not possible in JavaScript as there are (almost) no variable types.

How about introducing syntax check to alpine?

```
find src/ test/ -type f -name "*.js" -print0 | xargs -t -0 -L1 -P4 -- node_modules/.bin/acorn --silent --module --ecma10
```

Which is the earliest ECMA Edition alpine runs on?

**Comment by szepeviktor** [comment]
I see! Babel processes even ECMAScript 2020.
https://babeljs.io/blog/2020/01/11/7.8.0

**Comment by SimoTod** [comment]
Hi, Alpine is transpiled by Babel/rollup during the build process. Syntax errors would already cause a build to fail (it's a bit different from php or normal js where what you write is what goes into production) so I don't think we need an additional step for this.

**Comment by HugoDF** [comment]
@szepeviktor there's 2 Alpine.js builds, one that supports IE11 and a modern one

In the case of Alpine, there's a compilation/bundling step which runs the source through a JavaScript parser in order to compile away features in a backwards compatible manner (especially for IE11).

So syntax is actually checked by full code parsing at build time. What's more the test step runs against the compiled output so that would fail if there was a syntax error.

**Comment by szepeviktor** [comment]
Thank you for your response.
