### ISSUE TITLE
Alpine with Mapbox popup

### ISSUE THREAD

**Issue by fredcarle** [alpinejs/alpine#480]
Here is an interesting situation I came across. In the codepen bellow, I've added 3 buttons. One is in its own div and console logs upon @click. The 2 others are located inside the popup that you get upon clicking the Washington monument image.

On the alpine button, clicking will result with 2 console logs while the standard button will only print one console log.

https://codepen.io/fcarle/pen/xxwJwdo

Does anyone have any idea why that might be?

**Comment by SimoTod** [comment]
I don't know the technical reason, it might be a design incompatibility between Alpine and Mapbox. I assume mapbox does something on the line of "it does not destroy the html but it just detach it and reattach it, Alpine thinks it's a new element, it revaluates the @click and attach a new listener on the current component" but since it's about the interaction with a third party library, I can't give you a definitive answer.

As a workaround, if you define x-data inside your popup, it seems to work (I guess in that case Alpine creates a new component every time).

If you need to communicate with the parent component (which I bet you do), it will add a bit of complexity because you have to dispatch events. Hoevere, it's an established pattern in Alpine and you'll find examples in old issues.

I've also drafted an example here applied to your demo: https://codepen.io/SimoTod/pen/WNQKrMB
I hope it helps.

**Comment by fredcarle** [comment]
As always, thank you for your help @SimoTod. I had never used the $dispatch pattern but I can see how useful it can be. That work around will be just fine for my needs.
