### ISSUE TITLE
Wrong option selected on init (x-for usage in select)

### ISSUE THREAD

**Issue by hkan** [alpinejs/alpine#495]
There are some issues with which option is selected when select's options are generated with `x-for`. See pen for demo.

Pen: https://codepen.io/hkanaktas/pen/vYNVJYL?editors=1000

## Expected behavior

Both selects should display "cucumbers" after the page loads and Alpine initiates component.

## Observed behavior

The select with a static option (after `x-for`'d options) shows the static option as selected. Other one shows the first available option as selected.

## Notes

See how selects get correct option selected when you cause any changes in component data. Maybe this issue can be solved by triggering a forced update after selects with `x-for`'d options are rendered?

**Comment by HugoDF** [comment]
Temporary workarounds:
- You can bind `:selected` on `option`
- you can set the value you `x-model` to after the render (using nextTick)

Not 100% it's a bug although I might check it out later

**Comment by hkan** [comment]
Re-setting the same value in `$nextTick` was the first thing I tried. It doesn't work. Binding `:selected` seems to work.

**Comment by SimoTod** [comment]
You can set the value in x-init https://codepen.io/SimoTod/pen/pojxdzE?editors=1000

The reason why it doesn't work is that Alpine parses the page top to bottom, it hits x-model and tries to set the value to cocumber but x-for hasn't happen yet so that value doesn't exist and the select value remain sets to empty. After that, it processes x-for and adds those options but none of them matches the empty value.
To see the valid selection you need to force a refresh changing any value in the data context. The more reasonable things is to set set value1 in a x-init callback which runs after the component has started so x-for has already generated the needed html.

**Comment by hkan** [comment]
Ah, makes sense. Thanks for the explanation Simone. Issue can be closed if it's a _wontfix_.

**Comment by SimoTod** [comment]
The only way would be to force a second refresh after a component has been initialised but it would have a performance impact so it's probably a `wontfix` for now. Maybe @HugoDF or @ryangjchandler can write a blog on this topic in the next few weeks.

**Comment by HugoDF** [comment]
I think binding to `selected` is probably the canonical way to do this since it doesn't cause a flash (that you would by setting the value in a `$nextTick` in `x-init`

**Comment by HugoDF** [comment]
Thanks to Simone for the explanation of Alpine.js internals: `x-model` is running before the `x-for` has run and therefore the option it needs to select doesn't exist. I'm closing this since I don't think this is something we'll fix as there's 2 userland working: 

1. bind `selected`
2. set the initial value for `x-model` inside of `x-init`.

When using `select` and using `x-for` to create the `option` elements you need to bind `selected` on the `option` in order for the right option to get selected.

```html
<div
  x-data="{ options: ['apples', 'oranges', 'cucumbers'], selected: 'cucumbers' }"
>
  <select x-model="selected">
    <template x-for="option in options" :key="option">
      <option
        x-bind:value="option" 
        x-text="option"
        x-bind:selected="option === selected"
      ></option>
    </template>
  </select>
</div>
```

See it in action at the following CodePen: https://codepen.io/hugodf/pen/yLeyMap?editors=1000

**Comment by JerryBels** [comment]
Hello, I was looking at something similar and it looks like the solution to set the initial value for x-model inside of x-init doesn't work in Alpine 3. Simply changing Alpine in the above codepen ( https://codepen.io/SimoTod/pen/pojxdzE?editors=1000 ) demonstrate the issue.

**Comment by SimoTod** [comment]
> Hello, I was looking at something similar and it looks like the solution to set the initial value for x-model inside of x-init doesn't work in Alpine 3. Simply changing Alpine in the above codepen ( https://codepen.io/SimoTod/pen/pojxdzE?editors=1000 ) demonstrate the issue. 

That example was for v2, please see upgrade notes: https://alpinejs.dev/upgrade-guide#x-init-no-callback
