### ISSUE TITLE
Trying to use within Webflow

### ISSUE THREAD

**Issue by mbaxter91288** [alpinejs/alpine#510]
Hi there,

I am trying to sprinkle some Alpine.js into a Webflow project that needs some more interactivity. I can add custom attributes to elements but Webflow doesn't like `.` or `@` symbols in the data attributes. Seems to be happy with `:` and `-` so I was wondering, for things like `x-on:click.away` Is there any chance I can change that to something like `x-on:click:away` or `x-on:click-away`?

I understand this isn't your issue, it's a limitation with Webflow, but saw a "custom directives" issue was raised and wondering if this could also be a possibility?

Thanks,
Mat

**Comment by mblarsen** [comment]
OT: What is Webflow?

**Comment by HugoDF** [comment]
@mbaxter91288 I don't think we'll be adding support for `-` or `:` separated event listener modifiers.

As far as I understand webflow uses React and that's why you can't use `@` or `.`, have you tried storing your Alpine components in a string and dangerously setting inner HTML?

I wrote a post about React - Alpine interop that might help.

https://codewithhugo.com/alpine-js-react/

**Comment by mbaxter91288** [comment]
@mblarsen is a visual code platform: [Webflow](https://webflow.com/)

@HugoDF pasting the code example directly into a HTML embed module for Webflow works:
```
<div x-data="{ open: false }">
    <button @click="open = true">Open Dropdown</button>

    <ul
        x-show="open"
        @click.away="open = false"
    >
        Dropdown Body
    </ul>
</div>
```
Got a simplified test project here: https://alpine-js-testing.webflow.io/

The first blue button dropdown is me adding the required data attributes through the Webflow interface and the second is simply an HTML embed.

Perhaps I need to style up the HTML output in Webflow, then implement some HTML embeds perhaps.

Thanks

**Comment by mbaxter91288** [comment]
Creating the HTML structure in Webflow first, styling it, then using that code in a HTML embed with Alpine.js attributes works. It also let's me still visually see the outcome in the editor, which is nice.

Thanks for the quick responses and sorry to waste your time.

Thanks,
Mat

**Comment by gijsroge** [comment]
I’m honestly very curious why you would want to use Alpinejs if React is already available. Isn’t Alpinejs made to mostly be used to enhance existing html without the need of loading a large framework like React? I Mean absolutley no disrespect I might juist nog see the use case for this 😄

**Comment by loomchild** [comment]
I think that using embeds might not be the best solution, since it's not possible to adjust the style later, which kind of defeats the purpose of visual coding IMHO. 

I managed to get it working with custom attributes and a simple script mapping attribute names and tags (WIP, but pretty usable): https://github.com/loomchild/webflow-alpinejs

I wrote full explanation in this article: https://medium.com/untitled-factory/webflow-alpine-js-d53d77e3293, and here's an example site: https://webflow.com/website/alpinejs-demo.
