### ISSUE TITLE
Array data is not kept in sync

### ISSUE THREAD

**Issue by tanthammar** [alpinejs/alpine#531]
I have a component that adds/removes items from an array, if it does not exist.
This is done in two places in the component.
The first one, catches the changes in the array, but the other one does not register the change.
As the second one keeps "tags" at its original state it is impossible to add an item that previously existed.

```blade
<div>
    <div x-data='{tags: @json($existingTags), newTag: ""}'>
            <div>
                <template x-for="tag in tags" x-bind:key="tag">
                        <span x-text="tag"></span>
                </template>

//here the check !tags.includes() is working. It catches the change of the tags array data.
                <input wire:model="search" name="search" placeholder="Add tag..."
                    x-on:keydown.enter.prevent="if (newTag.trim() !== '' && !tags.includes(newTag.trim())) tags.push(newTag.trim()); newTag = ''"
                    x-model="newTag">
            </div>
        <div class="flex items-center border">
            @foreach($options as $option)

//this one, keeps "tags" at its original state, thus not adding words that have been removed previously.
            <button x-on:click.prevent="if (!tags.includes('{{$option}}')) tags.push('{{$option}}')">{{$option}}</button>
            @endforeach
        </div>
    </div>
</div>
```

**Comment by ryangjchandler** [comment]
@tanthammar Using native array methods such as `Array.push()` can be quite temperamental.

If you could provide an MVP CodePen that reproduces the problem, that would also be great since the Blade code above can't be used/tested very quickly.

In the meantime, instead of using `.push()` you could instead do `tags = Array.concat(tags, ['{{ $option }}']]`, since this actually reassigns the value to `tags` and the reactivity core is more likely to pick it up.

**Comment by tanthammar** [comment]
Thank you that solved it :)
