### ISSUE TITLE
x-on support for passive event listeners

### ISSUE THREAD

**Issue by alex-page** [alpinejs/alpine#559]
I would love to see support for [passive event listeners](https://developers.google.com/web/updates/2016/06/passive-event-listeners). I imagine it working like:
```
<div @mousedown.passive="interactive = true">
```

It looks like it should be pretty easy to implement as `x-on` is already creating an event listener for the element.
https://github.com/alpinejs/alpine/blob/5181242588436f58c3ea19cd0e45d6dcbe29f853/src/directives/on.js#L22

_Originally posted by @alex-page in https://github.com/alpinejs/alpine/discussions/557_

**Comment by HugoDF** [comment]
Bear in mind the following:

- We'll need to add a polyfill for IE11, this one might do the trick https://github.com/cadwmaster/polyfill-passive-touch-events or this one https://github.com/lifaon74/events-polyfill (which means we can drop the custom event polyfill)
- when using options with addEventListener the call to removeEventListener needs to have the same options.

Otherwise all the code changes should be localised to the `on.js` file you've mentioned.

**Comment by carlmjohnson** [comment]
Google Lighthouse dings my site for not using a passive scroll listener and I don’t support IE11, so I would appreciate this.

**Comment by ryangjchandler** [comment]
Will look at a PR for this one this weekend.

**Comment by HugoDF** [comment]
@ryangjchandler did you end up working on this? I might pick this up at some point next week otherwise 😄

**Comment by ryangjchandler** [comment]
> @ryangjchandler did you end up working on this? I might pick this up at some point next week otherwise 😄 

Yeah, wrapping up the PR. Will submit tomorrow 🤙🏼

**Comment by alex-page** [comment]
@ryangjchandler just so we aren't blocking anyone are you able to put up a draft PR?

**Comment by ryangjchandler** [comment]
@alex-page didn't get around to doing this - @HugoDF did you wanna have a crack?

**Comment by HugoDF** [comment]
Sure thing
