### ISSUE TITLE
Using x-html and adding classes doesn't show css transitions

### ISSUE THREAD

**Issue by joostvanhoof** [alpinejs/alpine#621]
Let's say that an element gets its html like so:

`<div x-html="theHtml"></div>`

And that `theHtml` inserted is: `<p class="test" x-on:mouseenter="hover = 2" :class="{ 'test-hover': hover > 1 }"></p>`

Then we have a transition defined on the `.text` class, and the expected hover effect on `.text-hover`. The reason that I'm not using `.test:hover` directly in CSS is that I want to use some logic to apply classes to other elements as well, hence `hover > 1` above.

```
.test {
  transition: all .2s ease-in-out;
}
.test-hover {
  transform: scale3d(1.3, 1.3, 1.3);
}
```

If I put the html in the `div` directly without using `x-html`, the transition effect is visible. If the html is placed in the `div` by using `x-html`, the effect is not visible.

I'm not sure why this is, maybe because AlpineJS re-renders when for instance the hover value changes and therefore the CSS effects are not visible? This is beyond what I understand of the inner workings so hopefully someone can help.

**Comment by HugoDF** [comment]
I'm not sure if it's just a typo but it should be `x-on:mouseenter` not `x-onmouseenter`

**Comment by joostvanhoof** [comment]
Yep, that was typo, thanks for spotting. Just updated the issue.

**Comment by ryangjchandler** [comment]
Hey @joostvanhoof - I think you hit the nail on the head at the end of your OP. When the `hover` variable changes, Alpine will re-render the element and insert the HTML again and this will continue to happen for each state change.

Is there any reason you're using `x-html` instead of putting the node in as normal?

**Comment by joostvanhoof** [comment]
It comes from an API so it's being dynamically inserted

**Comment by SimoTod** [comment]
I'm a bit confused by the condition though. you set `hover = 2` on mouseenter so `hover > 1` is always true which means that `test:hover` would do the same thing right?

**Comment by joostvanhoof** [comment]
Probably should have provided some additional context. The inners of `x-html` are added dynamically, and it can be a 5 star rating. If you hover a star, the class is added to the star that you're hovering plus all stars before that. I want to remove this on mouse leave as well. Pure CSS had some drawbacks for doing this.

**Comment by SimoTod** [comment]
okay, in this case you can't really use x-html. it's more of a logic issue than a bug since Alpine is supposed to work in that way: With your snippet, the whole html is reactive so it gets reinserted every time something changes.

I assume you need to set the html content once and then you only want classes and attributes to be reactive right? 

You should be able to do something like 
```html
<div x-data="{hover: 0}" x-init="() => $refs.stars.innerHTML = yourHtmlItCouldBeAnApiCall">
    ...
    <div x-ref="stars">
    </div>
</div>
```

**Comment by joostvanhoof** [comment]
Yep that's how I'd use it. Thanks!
