### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript

### ISSUE THREAD

**Issue by gio00** [alpinejs/alpine#63]
Hi, 

i'm using alpinejs just to open and close the menu of the website with `x-data`, `x-show` and `x-bind:style` to animate a few things.  

Probably not directly related to this library but maybe someone can help me or maybe this will help someone else. Anyway It was working fine on local and then on the production server this error came out in the js console of the browser and of course the menu wasn't working.

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".
```

**Comment by gio00** [comment]
I had to had 'unsafe-eval' to the Content-Security-Policy settings in nginx.conf and well now it works, i'm not sure if this is ok.

**Comment by calebporzio** [comment]
Closing for now. Re-open if someone else runs into this and thinks it is a problem not specific to their setup. Thanks.

**Comment by Urthen** [comment]
This is almost absolutely related to this library, as the entire function of the library is attempting to execute arbitrary strings on the page as Javascript. I don't believe this library will work with any `Content-Security-Policy` not including the `unsafe-eval` directive. I'd also like to point out that there is a reason the directive is labeled `unsafe` and that all recommendations are that it not be used except in cases of legacy websites that are too much work to rewrite all at once.

**Comment by SimoTod** [comment]
@Urthen 
Yeah, since the javascript code lives outside a script tag, Alpine relies on `Function()` to evaluate it. 
VueJs suffers the same issue when using templates (https://vuejs.org/v2/guide/installation.html#CSP-environments).

Have you been able to exploit Alpine for a XSS attach?

**Comment by Urthen** [comment]
Note that rather than requiring `unsafe-eval` as a CSP bypass, Vue offers a workaround that doesn't require `unsafe-eval`.  

Just from reading the documentation, I'm rather alarmed at the potential. It's not so much that adding Alpine itself directly adds any XSS vulnerabilities, but adding Alpine opens a *whole new class* of potential vulnerabilities that developers will need to be careful about. 

A simple, naive example could be something like a tag/badge system which allows custom tags. One implementation could generate tags like `<div id="custom_label-mylabel">mylabel</div>`. If a malicious attacker instead named their label `mylabel" x-init="alert('hey there neighbor')`, which may pass through many current user input sanitization schemes (unless you have developed a custom one for Alpine).

**Comment by Urthen** [comment]
This is especially problematic because these XSS attacks can occur *anywhere on any page that uses Alpine*, not just in areas which are using Alpine itself. If a page is dynamically generated on the server using user input sanitization typically geared for XSS or SQL injection attacks, it's quite easy to imagine missing Alpine injection attacks.

**Comment by SimoTod** [comment]
I'm not the author of the library, I just throw the odd PRs when I see I can help. :)
I understand your concern, hence the question since I'm genuinely interested.

Eval is used here https://github.com/alpinejs/alpine/blob/master/src/utils.js#L61 and here https://github.com/alpinejs/alpine/blob/master/src/utils.js#L67.

I'll see if I can create an exploit using the scenario that you described.

P.s. Vue offers a workaround but it sacrifices templates (so all your code needs to go in a JS file and it can't go directly in your HTML) which obviously limits the library a bit. 
Since Alpine works only using code in your HTML, I'm not sure we can have a workaround.

**Comment by SimoTod** [comment]
@Urthen It doesn't look exploitable, at least not in a simple way.

https://codepen.io/SimoTod/pen/BaNQRXp

I tried both `alert('ok')` which should bind a listener to the second button and `" x-on:click="alert('ok')" which should bind a listener on the first button.
The second example doesn't work because the quote is escaped.
A test to make sure that future changes won't remove this behaviour would probably help.

The first example looks a bit more dangerous but it doesn't work at the moment, probably due to the way listener are built. We could maybe disallow to use x-* attributes in an x-bind directive as a precautionary measure.

x-init would run only when a component is created so you would need to inject a whole chunk of HTML containing x-data but again, the escaping we said above would stop you.

I was also thinking that eval(well, Function()) by itself is not a real threat as long as the CSP policies are well configured blocking stuff like external connection and unauthorised third party libraries.
For example `https://csp-evaluator.withgoogle.com/only` flags it as a possible 'severity medium'.

I'll keep trying in the next days but it seems more a theoretical issue at the minute.

**Comment by swanprincess386** [comment]
> Hi,
> 
> i'm using alpinejs just to open and close the menu of the website with `x-data`, `x-show` and `x-bind:style` to animate a few things.
> 
> Probably not directly related to this library but maybe someone can help me or maybe this will help someone else. Anyway It was working fine on local and then on the production server this error came out in the js console of the browser and of course the menu wasn't working.
> 
> ```
> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".
> ```

**Comment by swanprincess386** [comment]
> @Urthen It doesn't look exploitable, at least not in a simple way.
> 
> https://codepen.io/SimoTod/pen/BaNQRXp
> 
> I tried both `alert('ok')` which should bind a listener to the second button and `" x-on:click="alert('ok')" which should bind a listener on the first button.
> The second example doesn't work because the quote is escaped.
> A test to make sure that future changes won't remove this behaviour would probably help.
> 
> The first example looks a bit more dangerous but it doesn't work at the moment, probably due to the way listener are built. We could maybe disallow to use x-* attributes in an x-bind directive as a precautionary measure.
> 
> x-init would run only when a component is created so you would need to inject a whole chunk of HTML containing x-data but again, the escaping we said above would stop you.
> 
> I was also thinking that eval(well, Function()) by itself is not a real threat as long as the CSP policies are well configured blocking stuff like external connection and unauthorised third party libraries.
> For example `https://csp-evaluator.withgoogle.com/only` flags it as a possible 'severity medium'.
> 
> I'll keep trying in the next days but it seems more a theoretical issue at the minute.
