### ISSUE TITLE
x-spread not working when alpine v2.3.5 loaded from the cdn

### ISSUE THREAD

**Issue by nerdroid23** [alpinejs/alpine#670]
Pretty much what the title says. I was able to get it to work using the 2.x.x version tho. I am not sure whether this is a bug or if i am doing something wrong. Just wanted to put this here in case someone else encounters that issue

**Comment by nerdroid23** [comment]
nevermind, i see that the version was bumped to 2.5.0 in the changelog but the documentation has the cdn links with the 2.3.5 version

**Comment by SimoTod** [comment]
The documentation just says to pin to a specific version when using in prod and it shows an example using 2.3.5. If you want a different version, you can use a different number in that link. 
X-spread was introduced in 2.4.0 (see release notes https://github.com/alpinejs/alpine/releases).
If you are not sure, you can ask in the discussion tab, it's better then reporting a false bug because it makes harder for other people to find genuine issues. I hope it makes sense.

**Comment by nerdroid23** [comment]
Yes, it definitely makes sense. I just wasn't sure whether it was a mistake in the docs. Thanks for the quick reply, I'll go ahead and close this now.

**Comment by SimoTod** [comment]
No worries, feel free to open a PR and suggest a wording change if you don't find that paragraph clear. Bear in mind that we don't want to update the readme every release so it was to be a generic message. What we want to communicate is that people should pin to a specific version in production so if a new release comes out with a regression, their production website won't break.

**Comment by KevinBatdorf** [comment]
I wonder if that could be automated using GitHub actions to replace it with the current release version. 

It probably is confusing to anyone not aware of the current released version number, but also would be tedious to update every time.
