### ISSUE TITLE
x-model does not update on form reset

### ISSUE THREAD

**Issue by baptiste0928** [alpinejs/alpine#686]
Hello everyone! 👋 

I've just started a project with Alpine, and I'm having a problem. I have created different buttons, which are **linked to a radio input via x-model**. These fields are in a form with a reset button. When I reset my form, the input fields change, but **the buttons managed by Alpine do not change**. 😖 

**I quickly made a JSFiddle** to show the problem: https://jsfiddle.net/7Lkwmp42/2/. Try changing the option via the list and then reset the form.

![WSB60Ki11a](https://user-images.githubusercontent.com/22115890/89104376-51363780-d419-11ea-953d-dd92889393ef.gif)

I also have to set a default value for the `option' variable, which doesn't take the value of the radio buttons at initialization.

Thank you in advance to all those who will help me! 😀

**Comment by SimoTod** [comment]
If you are using a reactive framework like alpine, you are overriding the standard dom. Your default value needs to be set on your alpine properties used by x-model otherwise when Alpine kicks in, it will override your default value. The reset thing is a nice to have but not supported at the minute so you need to add an x-click to reset your models.

**Comment by ryangjchandler** [comment]
@baptiste0928 - you can listen for the `reset` event on the `<form>` element too, as well as the `click` event on the button.

**Comment by ryangjchandler** [comment]
Hi @baptiste0928 - I'm going to close this issue since this isn't a bug / problem with Alpine.

**Comment by baptiste0928** [comment]
No worries, thank you for your answers! 😀
