### ISSUE TITLE
Wait Transition to finish before showing x-show

### ISSUE THREAD

**Issue by surjithctly** [alpinejs/alpine#721]
Hello,

I have a strange issue while trying to animate Tabs. I have 3 buttons for tabs, and 3 div's to display content. But when I add transition to the content. It breaks. See the below fiddle to see what I mean.

https://jsfiddle.net/0mv8husn/1/

How do I let other tab wait for the transition to finish before showing?

I have seen the pull #177 but this is not working. 

<details><summary>View Code</summary>
<p>

```html
 <div x-data="{ open: 'tab1' }">
   <button @click.prevent="open= 'tab1'">
     Open Tab 1
   </button>

   <button @click.preventk="open= 'tab2'">
     Open Tab 2
   </button>

   <button @click.prevent="open= 'tab3'">
     Open Tab 3
   </button>

   <div x-show="open === 'tab1'">
     Hey I'm tab 01
     <div x-show="open === 'tab1'" x-transition:enter-start="opacity-0 scale-90" x-transition:enter="ease-out transition-slow" x-transition:enter-end="opacity-100 scale-100" x-transition:leave-start="opacity-100 scale-100" x-transition:leave="ease-in transition-slow" x-transition:leave-end="opacity-0 scale-90">
       I'm transitioning 01
     </div>
   </div>

   <div x-show="open === 'tab2'">
     Hey I'm tab 02
     <div x-show="open === 'tab2'" x-transition:enter-start="opacity-0 scale-90" x-transition:enter="ease-out transition-slow" x-transition:enter-end="opacity-100 scale-100" x-transition:leave-start="opacity-100 scale-100" x-transition:leave="ease-in transition-slow" x-transition:leave-end="opacity-0 scale-90">
       I'm transitioning 02
     </div>
   </div>

   <div x-show="open === 'tab3'">
     Hey I'm tab 03
     <div x-show="open === 'tab3'" x-transition:enter-start="opacity-0 scale-90" x-transition:enter="ease-out transition-slow" x-transition:enter-end="opacity-100 scale-100" x-transition:leave-start="opacity-100 scale-100" x-transition:leave="ease-in transition-slow" x-transition:leave-end="opacity-0 scale-90">
       I'm transitioning 03
     </div>
   </div>
 </div>
```

</p>
</details>

**Comment by TheRealThor** [comment]
I have the same behaviour when doing transition with x-show where the expression is evaluated more than one time, like in the example with tabs. 

```
 <div x-show.transition = "activeTab === 1">Test1 </div>
 <div x-show.transition = "activeTab === 2">Test2 </div>
 <div x-show.transition = "activeTab === 3">Test3</div>
```
This will briefly show Test3 displaced underneath Test2, when activeTab becomes 2. This is because the change in activeTab triggers two transitions concurrently and hence displacing Test3 until Test2 was put to "display: none" after the transitions ended.   In jQuery I addressed this behaviour with: 

```
$('#tab1').fadeTo('slow',0).attr("style", "display: none");
```
which faded the DOM object out before it was set to display none. Afterwards another object could be faded in. 

I guess this could be a solution:
x-show checks if the left part of an expression is more than once to be evaluated. If so x-show transition will fire first where the expression(s) turned from true to false. Only once this element was put to "display: none" the transitions should be started on the DOM object(s) where the expression turned from false to true. Maybe the EventListener with 'transionend' can help here?
