### ISSUE TITLE
x-for Components

### ISSUE THREAD

**Issue by valluminarias** [alpinejs/alpine#793]
Hi.
I wanted to loop an array into components.
What I want to achieve is like this:

```
<template x-for="(el, index) in arr">

    <div x-data="{}">
        // Component Data
        ...
          How can I retrieve the `el` variable in the loop?
        ...
    </div>

</template>
```

Please help.
Thanks.

**Comment by calebporzio** [comment]
Mmmm interesting.

At first glance, I'd say it's impossible because Alpine components can't access outside Alpine scope.

However, you might be able to accomplish this using the "Alpine Magic Helpers" package and the `$parent` magic property: https://github.com/alpine-collective/alpine-magic-helpers

**Comment by HugoDF** [comment]
Unfortunately `$parent` just refers to another instance.

I think you might be able to do this using the following codepen example: https://codepen.io/hugodf/pen/jOqRZjm

```
<div x-data="{ arr: [{ foo: 'bar' }] }">
  <template x-for="(el, index) in arr">
  <div :data-el="JSON.stringify(el)" :data-index="index">
    <div x-data="{ el: JSON.parse($el.parentElement.dataset.el), index: $el.parentElement.dataset.index }">
      <div>
        <p x-text="el.foo"></p>
        <p>Index: <span x-text="index"></span></p>
      </div>
    </div>
    </div>
  </template>
</div>
```

if you're interested in just data, you can use `JSON.stringify/parse` + binding to data attributes to pass the data down, otherwise you can use `$parent` per Caleb's link + the index as per my example to do `$parent.arr[index]`

**Comment by KevinBatdorf** [comment]
@HugoDF You could still use `$parent` but in an equally "hacky" way, although perhaps more readable:
```html
<div x-data="{ letters: ['a', 'b', 'c'] }">
    <template x-for="(_thing, index) in letters">
        <div :data-current-index="index">
            <div
                x-data="{ index: $el.parentNode.dataset.currentIndex }"
                x-text="$parent.letters[index]">
            </div>
        </div>
    </template>
</div>
```
https://codepen.io/KevinBatdorf/pen/xxVeYea?editors=1000

**Comment by HugoDF** [comment]
Yeah I mention it at the bottom, the example has both, binding the data and setting the index

**Comment by valluminarias** [comment]
@HugoDF Thanks. That's helpful.
I tried the https://github.com/alpine-collective/alpine-magic-helpers `$parent`, but I didn't managed it to work.

**Comment by smbdelse** [comment]
[Here](https://github.com/alpine-collective/alpine-magic-helpers/discussions/27#discussioncomment-137474) I wrote some workaround for this problem using Spruce. 

Also I'm thinking if something like custom attribute could be provided, like this rough solution:
https://codepen.io/KamilDyrek/pen/dypoPjo

**Comment by kisscodes1909** [comment]
Hi All, Can we have best solution for it ?

**Comment by SimoTod** [comment]
@kisscodes1909 This is the simplest way with Alpine V2: https://codepen.io/SimoTod/pen/PoWYONg
It only works if x-data is on the loop element.

For example
```html
<template x-for="(el, index) in arr">
    <div x-data="{}">...</div> <!-- works -->
</template> 
 
<template x-for="(el, index) in arr">
    <div>
        <div x-data="{}">...</div><!-- does not work -->
    </div>
</template> 
```

If there is enough demand, we can create a $loop helper to https://github.com/alpine-collective/alpine-magic-helpers that would work at any level and where you can access $loop.current, $loop.index, etc  (let us know on that repo since it's not a community project)

**Comment by kisscodes1909** [comment]
Hi @SimoTod, It's great. I tried it and it worked. I think it is necessary because we need the component in the loop. I hope you put $loop helper to alpine magic helpers soon. Have a great day @SimoTod
