### ISSUE TITLE
x-for doesn't work properly on IE11

### ISSUE THREAD

**Issue by carljia999** [alpinejs/alpine#827]
The items in <template> don't show up and you can find various "Unhandled promise rejection" errors in dev tools console. 

I did some investigation and concluded it's related to template polyfill that's required on IE11, 2 problems were found,

1. the first one appears to be a template polyfill code bug (or an IE bug), but it can be fixed. I post fix code only for your information.

`-        template.content = contentDoc.createDocumentFragment();`
`+       template.content = document.createDocumentFragment();`
`         var child;`
`         while ((child = template.firstChild)) {`
`           capturedAppendChild.call(template.content, child);`

2. the second one is related to initialization step of alpinejs, 

By default (without defining window.deferLoadingAlpine ) alpinejs initializes before template polyfill bootstrap runs which is wrapped in DOMContentLoaded event handler, thus alpinejs is accessing template object before it's "polyfilled", please refer to the template polyfill doc.
[https://github.com/webcomponents/polyfills/tree/master/packages/template#known-limitations](doc)

I fixed my application with this
`window.deferLoadingAlpine = function(callback) {
	document.addEventListener('DOMContentLoaded', callback);
}`

I report this problem in the hope that you might have a better solution.
Thanks for you great work on alpine.

**Comment by djglxxii** [comment]
@carljia999 Carljia, where did you apply these changes for both bullets 1 and 2?  I am having what I presume is the same problem as you.  I am attempting to load a polyfill and I'm experiencing a situation where it sometimes works and sometimes not.  If I keep refreshing the page 'x-for' will occasionally work, so I suspect the issue is with initialization as you outlined in point 2.
