### ISSUE TITLE
x-for issue with numbers

### ISSUE THREAD

**Issue by talvbansal** [alpinejs/alpine#839]
Hi, 

I just noticed a bug with the latest alpine build (2.7.1) that doesn't affect versions prior.

If you x-for over and array of numerical values the first item always has a value of 1 when the array length is 1. Once the Array length is over 1 behaviour goes back to normal.

Here a code pen for it:

https://codepen.io/mariusaustr/pen/vYKydLy?editors=1001

Add a value that isn't 1 into input field and see that its rendered at 1. On the second addition the numbers return to normal.

**Comment by ryangjchandler** [comment]
@talvbansal This is being caused by a PR I made and some rather annoying JavaScript behaviour, where an array of length 1 that contains a number returns false when run through `isNaN()`.

I'll open a PR for a fix.

**Comment by ryangjchandler** [comment]
@talvbansal Please see the pull request that I've just opened. I've forked your original CodePen and updated it to use my script from the branch, see here: https://codepen.io/ryangjchandler/pen/ZEOBrJN?editors=1011

Going to /cc @calebporzio here too, because this is a regression and will need another patch release.

**Comment by talvbansal** [comment]
Perfect looking good @ryangjchandler , thanks for such a prompt fix, i was training someone today and couldnt work out why something so basic wouldn't work :joy:
