### ISSUE TITLE
Alpine data x-text/x-html not updating with .find()

### ISSUE THREAD

**Issue by jjjrmy** [alpinejs/alpine#932]
https://laravelplayground.com/#/snippets/858a44c4-89cf-4ece-9efb-9c988b0c8092

I am using Alpine to access data from outside of a Livewire component with `.find()`.
It is getting the data properly and updating the data on the browser event. You can see this in the console because it is outputting the name. The issue is that the `x-text` is not updating with the data even though it is being updated in Alpine. 
(You have to open the iframe in it's own tab to see the console.)

1. When it's only Alpine, without the `.find()` it updates the `x-text` fine.
2. When you click the 'Update' button it updates the Livewire data but not the `x-text` (I don't think this should be happening)
3. When you type in the Input it updates the Livewire data but not the `x-text`
4. If you click the 'Update' button then click the 'Alpine Only' button **both** the `x-text`s will update.

**Expected Behavior:**
When the event is fired and the `quiz` object is updated by the `.find()`, the `x-text` should update with the data.

**Comment by ryangjchandler** [comment]
@jjjrmy Is there any particular reason you're using `window.Livewire.find()`... instead of `@this` or `$wire`? The playground examples shows the Alpine root being on the `<body>`, so I guess that's why..

**Comment by ryangjchandler** [comment]
I'm guessing the problem comes down to this Livewire file: https://github.com/livewire/livewire/blob/master/js/component/SupportAlpine.js

Livewire is saying that if the Alpine component is the **child** of a Livewire component (an element that satisfies `[wire:id]`), it will setup Livewire event listeners to ensure the Alpine component is updated when any Livewire state changes.

In your instance, I believe you should either be dispatching a browser event from the Livewire side when it updates and then updating the name property manually, or instead moving the Alpine components elsewhere so that you can take advantage of `$wire` or `@entangle`, since those are designed for your desired outcome.

**Comment by jjjrmy** [comment]
@ryangjchandler All of this code worked previously and some update ago it does not work. The point is to access the data of the component outside of the component itself, so `@entangle` and `$wire` I don't think will work.

**Comment by ryangjchandler** [comment]
Do you know which version of Livewire this previously worked in?

**Comment by SimoTod** [comment]
It's unlikely to be an Alpine bug because it's just a normal assignment, right? Maybe you'll have more luck opening the ticket in the livewire board. It could be that at the time the event is triggered, the livewire data is not fully updated on the frontend.

**Comment by jjjrmy** [comment]
> Do you know which version of Livewire this previously worked in?
@ryangjchandler 

It was working as of June. I don't remember the exact version number of both Alpine & Livewire

**Comment by jjjrmy** [comment]
> It's unlikely to be an Alpine bug because it's just a normal assignment, right? Maybe you'll have more luck opening the ticket in the livewire board. It could be that at the time the event is triggered, the livewire data is not fully updated on the frontend.
@SimoTod 

If you check the example in the playground link you'll see that the data is being updated and it's being logged in the console during the event, so it has the updated data for sure. But it's not updating in the `x-text`.

**Comment by SimoTod** [comment]
I still think it's a livewire issue. Alpine doesn't have any custom code and what you do it's just an assignment. The reactivity in alpine only works if the variable changes and only if it goes through the proxy layers. Something must have changed in livewire so wither the reactivity happens too early (but it doesn't seem the case from what you said, I'm on my phone so I can't easily check) or the variable is updated earlier without going through the proxies so the assignment doesn't do anything and doesn't trigger un update. 🤷‍♂️

**Comment by jjjrmy** [comment]
> I still think it's a livewire issue. Alpine doesn't have any custom code and what you do it's just an assignment. The reactivity in alpine only works if the variable changes and only if it goes through the proxy layers. Something must have changed in livewire so either the reactivity happens too early (but it doesn't seem the case from what you said, I'm on my phone so I can't easily check) or the variable is updated earlier without going through the proxies so the assignment doesn't do anything and doesn't trigger un update. 🤷‍♂️
@SimoTod 

I can move this issue to Livewire but the same people will just respond, and it's more of an issue of Livewire AND Alpine.
On my example, the `console.log` outputs the data fine but name on the page does not update `x-text="quiz.name"`:
```x-on:dis.document="quiz = window.livewire.find(document.getElementById('Quiz').getAttribute('wire:id')); console.log(quiz.name);"```

**Comment by SimoTod** [comment]
I don't think they will. However you mentioned that it used to work. Which version?
Also, of you put the console log before the assignment, what does it print out?

**Comment by jjjrmy** [comment]
> I don't think they will. However you mentioned that it used to work. Which version?
> Also, of you put the console log before the assignment, what does it print out?
@SimoTod 

We can say it was version v1.3.1
It outputs the same data before or after the assignment on the update-event.
If I remove the assignment it logs the updated data, making me think there is some "magic" that is not working as planned.
But clearly if the data is correct in the console.log then the data is updated in Alpine, just not updating on the page.

**Comment by jjjrmy** [comment]
This is how it worked back on the later version, now this code is not working.
```js
x-data="{ quiz: window.livewire.find(document.getElementById('Quiz').getAttribute('wire:id')).data }"
x-on:next-step.document="quiz = window.livewire.find(document.getElementById('Quiz').getAttribute('wire:id')).data"
```

**Comment by ryangjchandler** [comment]
@jjjrmy Are you on Livewire v2 now?

**Comment by jjjrmy** [comment]
> @jjjrmy Are you on Livewire v2 now?
Yes

**Comment by ryangjchandler** [comment]
> > Are you on Livewire v2 now?
> > @ryangjchandler
> 
> Yes

IIRC v2 changed the internals quite a bit so that methods calls, etc are run async. Lets you do things like `await $wire.method()` so that could be your problem here really. 

@SimoTod is right though, this is less of an Alpine problem and more a Livewire<->Alpine compat problem.

**Comment by jjjrmy** [comment]
> IIRC v2 changed the internals quite a bit so that methods calls, etc are run async. Lets you do things like `await $wire.method()` so that could be your problem here really.
@ryangjchandler

So there is no solution other than move my issue to Livewire?
I am just looking to access data of a component outside of Livewire itself.

**Comment by ryangjchandler** [comment]
> > IIRC v2 changed the internals quite a bit so that methods calls, etc are run async. Lets you do things like `await $wire.method()` so that could be your problem here really.
> > @ryangjchandler
> 
> So there is no solution other than move my issue to Livewire?
> I am just looking to access data of a component outside of Livewire itself.

Yeah, but this repository is for Alpine issues. This is a problem with how Livewire is integrating with Alpine and should therefore be handled over there. 

You are also using a way that isn't officially recommended or supported, those are `@entangle` or `$wire`, as per the docs.

**Comment by jjjrmy** [comment]
> You are also using a way that isn't officially recommended or supported, those are `@entangle` or `$wire`, as per the docs.
@ryangjchandler

Both of those options to my understanding are for INSIDE of the component.

**Comment by ryangjchandler** [comment]
> > You are also using a way that isn't officially recommended or supported, those are `@entangle` or `$wire`, as per the docs.
> > @ryangjchandler
> 
> Both of those options to my understanding are for INSIDE of the component.

That's right. There isn't a "correct" way of accessing a Livewire component's data **outside** of a component so problem do crop up. 

I'm still of the opinion that this is a Livewire problem though. The Livewire component isn't telling Alpine to update after the new state is received from the server, etc.

**Comment by SimoTod** [comment]
@jjjrmy to clarify, I'm suggesting to open an isie there because the integration is in the livewire codebase. I have very little knowledge of Livewire's internals so people there might know better how to help you. Having an issue on a repository is not a problem, open source projects expect people to flag issues and bugs. As long as the issie makes sense, it's well described and repetible, nobody will close down the topic without providing at least an alternative approach.

**Comment by SimoTod** [comment]
@jjjrmy right, so I opened the codepen. 

`quiz` is a reference to the livewire object. When you update it using livewire, the object gets updated (by livewire, it doesn't go through the alpine proxy so it doesn't trigger the reactivity) then Alpine receives the event and runs the listener but, at that point, nothing changes (it refers to the same object, all data are already updated) so it doesn't trigger any DOM updates.

The code you posted is kinda hacky, you are trying to get the internal livewire data and assign it to an alpine variable but in v2 that object is a different proxy and if you modify values there, you are triggering a livewire update as well. This approach may or may not be the one you want.
You already know that having an alpine object on the body is not a good idea so I won't insist on this point. ;)

Since your code is hacking into livewire without using the public api, I don't think it will be considered a bug so you should probably change your approach.

Possible solutions:
- you stick to the hacky way. You just need to insert a control variable in x-data and update it using a new value every time you want to force a refresh. See: https://laravelplayground.com/#/snippets/f5087340-3f49-4886-b103-fd61048af57a
- you rearrange your code (assuming you don't want to update livewire from alpine). For example, you don't assign the livewire proxy to `quiz` but you build a new object starting from livewire data (you can do it in x-init to avoid calling find multiple times). In your event listener, you can then update the property you need. I would also suggest passing the properties in the dispatched event rather than reading them from the livewire internals because, as you noticed, they might change at any time.

**Comment by jjjrmy** [comment]
> In your event listener, you can then update the property you need. I would also suggest passing the properties in the dispatched event rather than reading them from the livewire internals because, as you noticed, they might change at any time.
@SimoTod 

Thank you! I ended up going with this solution, passing the data back with the event.

I'm going to close this issue here but leave it open on Livewire because even though my solution is not officially supported, I think something is not functioning right in my example.
